// Code generated by ent, DO NOT EDIT.

package openuem_ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/doncicuto/openuem_ent/component"
)

// Component is the model entity for the Component schema.
type Component struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Hostname holds the value of the "hostname" field.
	Hostname string `json:"hostname,omitempty"`
	// Arch holds the value of the "arch" field.
	Arch string `json:"arch,omitempty"`
	// Os holds the value of the "os" field.
	Os string `json:"os,omitempty"`
	// Component holds the value of the "component" field.
	Component component.Component `json:"component,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel component.Channel `json:"channel,omitempty"`
	// UpdateStatus holds the value of the "update_status" field.
	UpdateStatus component.UpdateStatus `json:"update_status,omitempty"`
	// UpdateMessage holds the value of the "update_message" field.
	UpdateMessage string `json:"update_message,omitempty"`
	// UpdateWhen holds the value of the "update_when" field.
	UpdateWhen   time.Time `json:"update_when,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Component) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case component.FieldID:
			values[i] = new(sql.NullInt64)
		case component.FieldHostname, component.FieldArch, component.FieldOs, component.FieldComponent, component.FieldVersion, component.FieldChannel, component.FieldUpdateStatus, component.FieldUpdateMessage:
			values[i] = new(sql.NullString)
		case component.FieldUpdateWhen:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Component fields.
func (c *Component) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case component.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case component.FieldHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hostname", values[i])
			} else if value.Valid {
				c.Hostname = value.String
			}
		case component.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				c.Arch = value.String
			}
		case component.FieldOs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os", values[i])
			} else if value.Valid {
				c.Os = value.String
			}
		case component.FieldComponent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field component", values[i])
			} else if value.Valid {
				c.Component = component.Component(value.String)
			}
		case component.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				c.Version = value.String
			}
		case component.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				c.Channel = component.Channel(value.String)
			}
		case component.FieldUpdateStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field update_status", values[i])
			} else if value.Valid {
				c.UpdateStatus = component.UpdateStatus(value.String)
			}
		case component.FieldUpdateMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field update_message", values[i])
			} else if value.Valid {
				c.UpdateMessage = value.String
			}
		case component.FieldUpdateWhen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_when", values[i])
			} else if value.Valid {
				c.UpdateWhen = value.Time
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Component.
// This includes values selected through modifiers, order, etc.
func (c *Component) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// Update returns a builder for updating this Component.
// Note that you need to call Component.Unwrap() before calling this method if this Component
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Component) Update() *ComponentUpdateOne {
	return NewComponentClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Component entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Component) Unwrap() *Component {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("openuem_ent: Component is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Component) String() string {
	var builder strings.Builder
	builder.WriteString("Component(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("hostname=")
	builder.WriteString(c.Hostname)
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(c.Arch)
	builder.WriteString(", ")
	builder.WriteString("os=")
	builder.WriteString(c.Os)
	builder.WriteString(", ")
	builder.WriteString("component=")
	builder.WriteString(fmt.Sprintf("%v", c.Component))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(c.Version)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", c.Channel))
	builder.WriteString(", ")
	builder.WriteString("update_status=")
	builder.WriteString(fmt.Sprintf("%v", c.UpdateStatus))
	builder.WriteString(", ")
	builder.WriteString("update_message=")
	builder.WriteString(c.UpdateMessage)
	builder.WriteString(", ")
	builder.WriteString("update_when=")
	builder.WriteString(c.UpdateWhen.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Components is a parsable slice of Component.
type Components []*Component
