// Code generated by ent, DO NOT EDIT.

package openuem_ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/doncicuto/openuem_ent/release"
)

// Release is the model entity for the Release schema.
type Release struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ReleaseType holds the value of the "release_type" field.
	ReleaseType release.ReleaseType `json:"release_type,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel string `json:"channel,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// ReleaseNotes holds the value of the "release_notes" field.
	ReleaseNotes string `json:"release_notes,omitempty"`
	// FileURL holds the value of the "file_url" field.
	FileURL string `json:"file_url,omitempty"`
	// Checksum holds the value of the "checksum" field.
	Checksum string `json:"checksum,omitempty"`
	// IsCritical holds the value of the "is_critical" field.
	IsCritical bool `json:"is_critical,omitempty"`
	// ReleaseDate holds the value of the "release_date" field.
	ReleaseDate time.Time `json:"release_date,omitempty"`
	// Os holds the value of the "os" field.
	Os string `json:"os,omitempty"`
	// Arch holds the value of the "arch" field.
	Arch string `json:"arch,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReleaseQuery when eager-loading is set.
	Edges        ReleaseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReleaseEdges holds the relations/edges for other nodes in the graph.
type ReleaseEdges struct {
	// Agents holds the value of the agents edge.
	Agents []*Agent `json:"agents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AgentsOrErr returns the Agents value or an error if the edge
// was not loaded in eager-loading.
func (e ReleaseEdges) AgentsOrErr() ([]*Agent, error) {
	if e.loadedTypes[0] {
		return e.Agents, nil
	}
	return nil, &NotLoadedError{edge: "agents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Release) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case release.FieldIsCritical:
			values[i] = new(sql.NullBool)
		case release.FieldID:
			values[i] = new(sql.NullInt64)
		case release.FieldReleaseType, release.FieldVersion, release.FieldChannel, release.FieldSummary, release.FieldReleaseNotes, release.FieldFileURL, release.FieldChecksum, release.FieldOs, release.FieldArch:
			values[i] = new(sql.NullString)
		case release.FieldReleaseDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Release fields.
func (r *Release) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case release.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case release.FieldReleaseType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_type", values[i])
			} else if value.Valid {
				r.ReleaseType = release.ReleaseType(value.String)
			}
		case release.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				r.Version = value.String
			}
		case release.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				r.Channel = value.String
			}
		case release.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				r.Summary = value.String
			}
		case release.FieldReleaseNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field release_notes", values[i])
			} else if value.Valid {
				r.ReleaseNotes = value.String
			}
		case release.FieldFileURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_url", values[i])
			} else if value.Valid {
				r.FileURL = value.String
			}
		case release.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				r.Checksum = value.String
			}
		case release.FieldIsCritical:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_critical", values[i])
			} else if value.Valid {
				r.IsCritical = value.Bool
			}
		case release.FieldReleaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field release_date", values[i])
			} else if value.Valid {
				r.ReleaseDate = value.Time
			}
		case release.FieldOs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os", values[i])
			} else if value.Valid {
				r.Os = value.String
			}
		case release.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				r.Arch = value.String
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Release.
// This includes values selected through modifiers, order, etc.
func (r *Release) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryAgents queries the "agents" edge of the Release entity.
func (r *Release) QueryAgents() *AgentQuery {
	return NewReleaseClient(r.config).QueryAgents(r)
}

// Update returns a builder for updating this Release.
// Note that you need to call Release.Unwrap() before calling this method if this Release
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Release) Update() *ReleaseUpdateOne {
	return NewReleaseClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Release entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Release) Unwrap() *Release {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("openuem_ent: Release is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Release) String() string {
	var builder strings.Builder
	builder.WriteString("Release(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("release_type=")
	builder.WriteString(fmt.Sprintf("%v", r.ReleaseType))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(r.Version)
	builder.WriteString(", ")
	builder.WriteString("channel=")
	builder.WriteString(r.Channel)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(r.Summary)
	builder.WriteString(", ")
	builder.WriteString("release_notes=")
	builder.WriteString(r.ReleaseNotes)
	builder.WriteString(", ")
	builder.WriteString("file_url=")
	builder.WriteString(r.FileURL)
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(r.Checksum)
	builder.WriteString(", ")
	builder.WriteString("is_critical=")
	builder.WriteString(fmt.Sprintf("%v", r.IsCritical))
	builder.WriteString(", ")
	builder.WriteString("release_date=")
	builder.WriteString(r.ReleaseDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("os=")
	builder.WriteString(r.Os)
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(r.Arch)
	builder.WriteByte(')')
	return builder.String()
}

// Releases is a parsable slice of Release.
type Releases []*Release
