// Code generated by ent, DO NOT EDIT.

package openuem_ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/doncicuto/openuem_ent/agent"
	"github.com/doncicuto/openuem_ent/predicate"
	"github.com/doncicuto/openuem_ent/systemupdate"
)

// SystemUpdateQuery is the builder for querying SystemUpdate entities.
type SystemUpdateQuery struct {
	config
	ctx        *QueryContext
	order      []systemupdate.OrderOption
	inters     []Interceptor
	predicates []predicate.SystemUpdate
	withOwner  *AgentQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SystemUpdateQuery builder.
func (suq *SystemUpdateQuery) Where(ps ...predicate.SystemUpdate) *SystemUpdateQuery {
	suq.predicates = append(suq.predicates, ps...)
	return suq
}

// Limit the number of records to be returned by this query.
func (suq *SystemUpdateQuery) Limit(limit int) *SystemUpdateQuery {
	suq.ctx.Limit = &limit
	return suq
}

// Offset to start from.
func (suq *SystemUpdateQuery) Offset(offset int) *SystemUpdateQuery {
	suq.ctx.Offset = &offset
	return suq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (suq *SystemUpdateQuery) Unique(unique bool) *SystemUpdateQuery {
	suq.ctx.Unique = &unique
	return suq
}

// Order specifies how the records should be ordered.
func (suq *SystemUpdateQuery) Order(o ...systemupdate.OrderOption) *SystemUpdateQuery {
	suq.order = append(suq.order, o...)
	return suq
}

// QueryOwner chains the current query on the "owner" edge.
func (suq *SystemUpdateQuery) QueryOwner() *AgentQuery {
	query := (&AgentClient{config: suq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := suq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := suq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(systemupdate.Table, systemupdate.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, systemupdate.OwnerTable, systemupdate.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(suq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SystemUpdate entity from the query.
// Returns a *NotFoundError when no SystemUpdate was found.
func (suq *SystemUpdateQuery) First(ctx context.Context) (*SystemUpdate, error) {
	nodes, err := suq.Limit(1).All(setContextOp(ctx, suq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{systemupdate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (suq *SystemUpdateQuery) FirstX(ctx context.Context) *SystemUpdate {
	node, err := suq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SystemUpdate ID from the query.
// Returns a *NotFoundError when no SystemUpdate ID was found.
func (suq *SystemUpdateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = suq.Limit(1).IDs(setContextOp(ctx, suq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{systemupdate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (suq *SystemUpdateQuery) FirstIDX(ctx context.Context) int {
	id, err := suq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SystemUpdate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SystemUpdate entity is found.
// Returns a *NotFoundError when no SystemUpdate entities are found.
func (suq *SystemUpdateQuery) Only(ctx context.Context) (*SystemUpdate, error) {
	nodes, err := suq.Limit(2).All(setContextOp(ctx, suq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{systemupdate.Label}
	default:
		return nil, &NotSingularError{systemupdate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (suq *SystemUpdateQuery) OnlyX(ctx context.Context) *SystemUpdate {
	node, err := suq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SystemUpdate ID in the query.
// Returns a *NotSingularError when more than one SystemUpdate ID is found.
// Returns a *NotFoundError when no entities are found.
func (suq *SystemUpdateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = suq.Limit(2).IDs(setContextOp(ctx, suq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{systemupdate.Label}
	default:
		err = &NotSingularError{systemupdate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (suq *SystemUpdateQuery) OnlyIDX(ctx context.Context) int {
	id, err := suq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SystemUpdates.
func (suq *SystemUpdateQuery) All(ctx context.Context) ([]*SystemUpdate, error) {
	ctx = setContextOp(ctx, suq.ctx, ent.OpQueryAll)
	if err := suq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SystemUpdate, *SystemUpdateQuery]()
	return withInterceptors[[]*SystemUpdate](ctx, suq, qr, suq.inters)
}

// AllX is like All, but panics if an error occurs.
func (suq *SystemUpdateQuery) AllX(ctx context.Context) []*SystemUpdate {
	nodes, err := suq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SystemUpdate IDs.
func (suq *SystemUpdateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if suq.ctx.Unique == nil && suq.path != nil {
		suq.Unique(true)
	}
	ctx = setContextOp(ctx, suq.ctx, ent.OpQueryIDs)
	if err = suq.Select(systemupdate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (suq *SystemUpdateQuery) IDsX(ctx context.Context) []int {
	ids, err := suq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (suq *SystemUpdateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, suq.ctx, ent.OpQueryCount)
	if err := suq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, suq, querierCount[*SystemUpdateQuery](), suq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (suq *SystemUpdateQuery) CountX(ctx context.Context) int {
	count, err := suq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (suq *SystemUpdateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, suq.ctx, ent.OpQueryExist)
	switch _, err := suq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("openuem_ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (suq *SystemUpdateQuery) ExistX(ctx context.Context) bool {
	exist, err := suq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SystemUpdateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (suq *SystemUpdateQuery) Clone() *SystemUpdateQuery {
	if suq == nil {
		return nil
	}
	return &SystemUpdateQuery{
		config:     suq.config,
		ctx:        suq.ctx.Clone(),
		order:      append([]systemupdate.OrderOption{}, suq.order...),
		inters:     append([]Interceptor{}, suq.inters...),
		predicates: append([]predicate.SystemUpdate{}, suq.predicates...),
		withOwner:  suq.withOwner.Clone(),
		// clone intermediate query.
		sql:       suq.sql.Clone(),
		path:      suq.path,
		modifiers: append([]func(*sql.Selector){}, suq.modifiers...),
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (suq *SystemUpdateQuery) WithOwner(opts ...func(*AgentQuery)) *SystemUpdateQuery {
	query := (&AgentClient{config: suq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	suq.withOwner = query
	return suq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SystemUpdate.Query().
//		GroupBy(systemupdate.FieldStatus).
//		Aggregate(openuem_ent.Count()).
//		Scan(ctx, &v)
func (suq *SystemUpdateQuery) GroupBy(field string, fields ...string) *SystemUpdateGroupBy {
	suq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SystemUpdateGroupBy{build: suq}
	grbuild.flds = &suq.ctx.Fields
	grbuild.label = systemupdate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status string `json:"status,omitempty"`
//	}
//
//	client.SystemUpdate.Query().
//		Select(systemupdate.FieldStatus).
//		Scan(ctx, &v)
func (suq *SystemUpdateQuery) Select(fields ...string) *SystemUpdateSelect {
	suq.ctx.Fields = append(suq.ctx.Fields, fields...)
	sbuild := &SystemUpdateSelect{SystemUpdateQuery: suq}
	sbuild.label = systemupdate.Label
	sbuild.flds, sbuild.scan = &suq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SystemUpdateSelect configured with the given aggregations.
func (suq *SystemUpdateQuery) Aggregate(fns ...AggregateFunc) *SystemUpdateSelect {
	return suq.Select().Aggregate(fns...)
}

func (suq *SystemUpdateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range suq.inters {
		if inter == nil {
			return fmt.Errorf("openuem_ent: uninitialized interceptor (forgotten import openuem_ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, suq); err != nil {
				return err
			}
		}
	}
	for _, f := range suq.ctx.Fields {
		if !systemupdate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("openuem_ent: invalid field %q for query", f)}
		}
	}
	if suq.path != nil {
		prev, err := suq.path(ctx)
		if err != nil {
			return err
		}
		suq.sql = prev
	}
	return nil
}

func (suq *SystemUpdateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SystemUpdate, error) {
	var (
		nodes       = []*SystemUpdate{}
		withFKs     = suq.withFKs
		_spec       = suq.querySpec()
		loadedTypes = [1]bool{
			suq.withOwner != nil,
		}
	)
	if suq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, systemupdate.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SystemUpdate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SystemUpdate{config: suq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(suq.modifiers) > 0 {
		_spec.Modifiers = suq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, suq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := suq.withOwner; query != nil {
		if err := suq.loadOwner(ctx, query, nodes, nil,
			func(n *SystemUpdate, e *Agent) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (suq *SystemUpdateQuery) loadOwner(ctx context.Context, query *AgentQuery, nodes []*SystemUpdate, init func(*SystemUpdate), assign func(*SystemUpdate, *Agent)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SystemUpdate)
	for i := range nodes {
		if nodes[i].agent_systemupdate == nil {
			continue
		}
		fk := *nodes[i].agent_systemupdate
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_systemupdate" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (suq *SystemUpdateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := suq.querySpec()
	if len(suq.modifiers) > 0 {
		_spec.Modifiers = suq.modifiers
	}
	_spec.Node.Columns = suq.ctx.Fields
	if len(suq.ctx.Fields) > 0 {
		_spec.Unique = suq.ctx.Unique != nil && *suq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, suq.driver, _spec)
}

func (suq *SystemUpdateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(systemupdate.Table, systemupdate.Columns, sqlgraph.NewFieldSpec(systemupdate.FieldID, field.TypeInt))
	_spec.From = suq.sql
	if unique := suq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if suq.path != nil {
		_spec.Unique = true
	}
	if fields := suq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemupdate.FieldID)
		for i := range fields {
			if fields[i] != systemupdate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := suq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := suq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := suq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := suq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (suq *SystemUpdateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(suq.driver.Dialect())
	t1 := builder.Table(systemupdate.Table)
	columns := suq.ctx.Fields
	if len(columns) == 0 {
		columns = systemupdate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if suq.sql != nil {
		selector = suq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if suq.ctx.Unique != nil && *suq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range suq.modifiers {
		m(selector)
	}
	for _, p := range suq.predicates {
		p(selector)
	}
	for _, p := range suq.order {
		p(selector)
	}
	if offset := suq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := suq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (suq *SystemUpdateQuery) Modify(modifiers ...func(s *sql.Selector)) *SystemUpdateSelect {
	suq.modifiers = append(suq.modifiers, modifiers...)
	return suq.Select()
}

// SystemUpdateGroupBy is the group-by builder for SystemUpdate entities.
type SystemUpdateGroupBy struct {
	selector
	build *SystemUpdateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sugb *SystemUpdateGroupBy) Aggregate(fns ...AggregateFunc) *SystemUpdateGroupBy {
	sugb.fns = append(sugb.fns, fns...)
	return sugb
}

// Scan applies the selector query and scans the result into the given value.
func (sugb *SystemUpdateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sugb.build.ctx, ent.OpQueryGroupBy)
	if err := sugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemUpdateQuery, *SystemUpdateGroupBy](ctx, sugb.build, sugb, sugb.build.inters, v)
}

func (sugb *SystemUpdateGroupBy) sqlScan(ctx context.Context, root *SystemUpdateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sugb.fns))
	for _, fn := range sugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sugb.flds)+len(sugb.fns))
		for _, f := range *sugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SystemUpdateSelect is the builder for selecting fields of SystemUpdate entities.
type SystemUpdateSelect struct {
	*SystemUpdateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sus *SystemUpdateSelect) Aggregate(fns ...AggregateFunc) *SystemUpdateSelect {
	sus.fns = append(sus.fns, fns...)
	return sus
}

// Scan applies the selector query and scans the result into the given value.
func (sus *SystemUpdateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sus.ctx, ent.OpQuerySelect)
	if err := sus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SystemUpdateQuery, *SystemUpdateSelect](ctx, sus.SystemUpdateQuery, sus, sus.inters, v)
}

func (sus *SystemUpdateSelect) sqlScan(ctx context.Context, root *SystemUpdateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sus.fns))
	for _, fn := range sus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (sus *SystemUpdateSelect) Modify(modifiers ...func(s *sql.Selector)) *SystemUpdateSelect {
	sus.modifiers = append(sus.modifiers, modifiers...)
	return sus
}
